### ISSUE TITLE
Dynamic Fees

### ISSUE THREAD

**Issue by eragmus** [Airbitz/airbitz-core#13]
Hi, various wallets (breadwallet, electrum, bitcoin core, ledger, mycelium, copay, bitgo) now have dynamic fees integrated by default. This is essential to help deal with future stress tests / spam attacks, one of which is impending (Coinwallet's plan to create a severe 30-day tx backlog in September).

What are Airbitz's thoughts? It may be prudent to prioritize this and have it out ASAP, given that September threat.

Thanks.

**Comment by Jacobbubble** [comment]
Airbitz's current miner fee is dynamic based on the transaction (file) size. A miner fee with lots of inputs will include an appropriate miner fee to get into the next block.

Miner fees were adjusted after the spam attack from about 100 bits to 300 bits.
This has ensured that transactions get in the next block, even during the spam attack.

Albeit it is a bit high for when there's no spam attack. Dynamic fees based on the blockchain's current state is in the pipeline though.

**Comment by eragmus** [comment]
> Dynamic fees based on the blockchain's current state is in the pipeline though.

Great, look forward to it, hopefully in time for the next attack (scheduled for Sep. 10)!

**Comment by paullinator** [comment]
Fees are now very dynamic and even more so than any other wallet as the fees factor how much a user is sending to help reduce fees for microtransactions. Airbitz pings electrum nodes to find the suggested network fees and chooses accordingly.

Closing
