### ISSUE TITLE
Checksum Error when building on Ubuntu 15.04

### ISSUE THREAD

**Issue by Jacobbubble** [Airbitz/airbitz-core#18]
When trying to build airbitz-core, I get a checksum error for openssl by default.
"checksum failed on path: expected 2c5691496761cb18f98476eefa4d35c835448fb6, got 89b28dc5f4cf2e8b59d974a867016748f9458589".

I was able to get past this issue in the build process by manually downloading OpenSSL and making deps/recipes/openssl/openssl.recipe 's "version="1.0.2f" to match the version I downloaded from OpenSSL.

Might just need to update the hardcoded download source/version.

**Comment by swansontec** [comment]
This is fixed on our public master branch.
