### ISSUE TITLE
Ability to spend unconfirmed inputs

### ISSUE THREAD

**Issue by FrancisPouliot** [Airbitz/airbitz-core#20]
In the settings (advanced users only) I would like to have the option to turn on sending unconfirmed inputs. I have to do this relatively frequently when moving funds from one of my own wallets to another.

I understand there are risks, which is why this should be burried in the settings.

**Comment by paullinator** [comment]
This is already possible. The wallet lets you spend unconfirmed funds UNLESS they are from an incoming RBF transaction, a double spend, or malleated transaction. Then it will require a confirmation.

**Comment by FrancisPouliot** [comment]
Can confirm you are correct, the error was because the fee was too high for my unconfirmed balance I didn't notice
