### ISSUE TITLE
RBF flag

### ISSUE THREAD

**Issue by FrancisPouliot** [Airbitz/airbitz-core#22]
I did an RBF transaction to the Airbitz wallet and it was not detected. I feel like there should be a flag, as it is the case in Mycelium

**Comment by paullinator** [comment]
Was this a direct RBF transaction or a non-RBF transaction spent from an RBF transaction. We definitely have RBF detection support and customers have pinged us when they see it. What did you use to craft the transaction so we can test it on our side.

**Comment by FrancisPouliot** [comment]
I was not able to reproduce this. I had crafted the tx with electrum.

Weird, because all my outbound transactions are RBF by default.

Perhaps it was a BIP70 payment request? Would that explain something?

**Comment by FrancisPouliot** [comment]
I think you can close this, unless you want me to investigate further. Perhaps it was at the same time I was testing the Electrum servers and something weird happened like the TX showing up as confirmed already when my connection to a functioning electrum server was re-established

**Comment by paullinator** [comment]
Ok. thanks. let us know if you find a reproducible case.
