### ISSUE TITLE
Please add NOK

### ISSUE THREAD

**Issue by sandakersmann** [Airbitz/airbitz-core#3]
Would be fantastic if you could add the Norwegian krone into your currency choices. Awesome wallet by the way :)

http://en.wikipedia.org/wiki/Norwegian_krone

**Comment by sandakersmann** [comment]
@paullinator Any news on this?

**Comment by paullinator** [comment]
It's slated for our next release which will be mid May. Keep an eye out for it. We'll be putting in every currency in the world for then.

**Comment by sandakersmann** [comment]
Got the update on my Android today. Great work by the team at Airbitz!
