### ISSUE TITLE
Small bitcoin transaction has not confirmed in over a week due to small miner fees

### ISSUE THREAD

**Issue by pikefloyd** [Airbitz/airbitz-core#6]
Playing about between different wallets, I've had two small transactions fail to confirm, (from 25th Feb 2015) due to the default miner fee in Airbitz. 

I'm unable to export private keys in Airbitz to import into another wallet and apply higher fees.

If this wallet is targeted for new users of bitcoin, they may also play about with small amounts and also have transactions fail to confirm. This may initially give them a negative bitcoin experience.

Please let me know if you would like any further information about the transactions.

**Comment by pikefloyd** [comment]
Is there any way to resolve this, (export private keys to import into another wallet, or resend transaction with higher fees) or will these transactions be listed as pending in the Airbitz wallet indefinitely?

**Comment by swansontec** [comment]
Sorry for not replying right away. The latest release of our app should have a fix for this, where we drop any transactions that don't appear in the blockchain after 24 hours.

**Comment by swansontec** [comment]
Also, I definitely need to make some kind of tool for dealing with the exported seeds. We have a tool at https://github.com/Airbitz/airbitz-core/blob/master/util/airbitz-keygen.sh, but it's not really documented or usable.

**Comment by pikefloyd** [comment]
That great, I look forward to trying out the new version. I also saw the video with one touch 2FA it looks really good. Thanks for all your efforts.

**Comment by swansontec** [comment]
Have you had a chance to try the latest version? Did it fix the problem?

**Comment by pikefloyd** [comment]
Yes, the new version updated earlier in the week. The funds became
available again and I resent. This time it confirmed in the next block.
Thanks again
 On 28 Mar 2015 07:18, "William Swanson" <notifications@github.com> wrote:

Have you had a chance to try the latest version? Did it fix the problem?

--
Reply to this email directly or view it on GitHub
<https://github.com/Airbitz/airbitz-core/issues/6#issuecomment-87183884>.

**Comment by swansontec** [comment]
Great, I'll mark this as resolved, then.
