### ISSUE TITLE
Airbitz 1.4.8 crashes on startup in genymotion emulator.

### ISSUE THREAD

**Issue by greatwolf** [Airbitz/airbitz-core#7]
When I start airbitz on the emulator it shows a grey screen and after a few seconds it shows me the error:

    Unfortunately, Airbitz has stopped.

This is installed into the running emulator through google play's app store as usual. A prior version of Airbitz did work but I'm not sure which new release broke this.

Info on emulator tested on:

 - Genymotion v2.4.0.
 - Moto X emulator profile
 - Android 4.4.4 running ARM translation patch + gapps-kk-20140105-signed.zip

I've tested this using older Android 4.3 as well as other emulator profile combinations like nexus and samsung -- they all exhibit the same startup crashing problem.

**Comment by teneighty** [comment]
What does logcat show? Did you have any issues compiling airbitz-core?

We have had issues with Genymotion but the ARM translation patch worked in the past. You can also try enabling x86 in the Application.mk and rerunning `mkabc` to build the x86 binaries.

**Comment by greatwolf** [comment]
I didn't try building airbitz-core from the git repo, I'm just using the compiled app from the google Play Store.

Here's what the logcat shows:

    G:\Genymotion\tools>adb shell
    root@vbox86p:/ # logcat -d | grep air
    logcat -d | grep air
    I/ActivityManager( 1122): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUN
    CHER] flg=0x10200000 pkg=com.airbitz cmp=com.airbitz/.activities.NavigationActivity bnds=[40,185][20
    0,385]} from pid 1529
    I/ActivityManager( 1122): Start proc com.airbitz for activity com.airbitz/.activities.NavigationActi
    vity: pid=3120 uid=10074 gids={50074, 3003, 1028, 1015, 3002, 3001}
    D/dalvikvm( 3120): Trying to load lib /data/app-lib/com.airbitz-1/libabc.so 0xa5051f60
    F/libc    ( 3120): Fatal signal 11 (SIGSEGV) at 0x000000b4 (code=1), thread 3120 (com.airbitz)
    I/DEBUG   (  132): pid: 3120, tid: 3120, name: com.airbitz  >>> com.airbitz <<<
    I/ActivityManager( 1122): Process com.airbitz (pid 3120) has died.
    I/ActivityManager( 1122): Start proc com.airbitz for activity com.airbitz/.activities.NavigationActi
    vity: pid=3136 uid=10074 gids={50074, 3003, 1028, 1015, 3002, 3001}
    D/dalvikvm( 3136): Trying to load lib /data/app-lib/com.airbitz-1/libabc.so 0xa5052ea0
    F/libc    ( 3136): Fatal signal 11 (SIGSEGV) at 0x000000b4 (code=1), thread 3136 (com.airbitz)
    I/DEBUG   (  132): pid: 3136, tid: 3136, name: com.airbitz  >>> com.airbitz <<<
    W/ActivityManager( 1122):   Force finishing activity com.airbitz/.activities.NavigationActivity
    I/WindowManager( 1122): Screenshot max retries 4 of Token{52a51164 ActivityRecord{52a47548 u0 com.ai
    rbitz/.activities.NavigationActivity t2 f}} appWin=Window{52a46d3c u0 Starting com.airbitz} drawStat
    e=4
    I/ActivityManager( 1122): Process com.airbitz (pid 3136) has died.
    root@vbox86p:/ #

**Comment by greatwolf** [comment]
Just wanted to report, I tested this with Droid4x 0.7.5 just now. Same problem; except it stays on the grey screen indefinitely.

**Comment by teneighty** [comment]
Thanks for the additional info. I am able to reproduce this. I am still trying to figure out what is wrong. Interestingly local builds of the APK install and run just fine on GenyMotion.

**Comment by greatwolf** [comment]
Just wanted to add 1.4.9 still exhibits the same crashing problem on startup. Are there any differences between the binaries produced from a local build vs the one that's submitted to google play store?

**Comment by teneighty** [comment]
Hi @greatwolf. Please try 1.5.2. We've just added x86 support so you shouldn't need the ARM translation patch.

**Comment by greatwolf** [comment]
Looks like version 1.5.2 works again on geny motion. Really appreciate the fix. Thank you!
